// constants/data.ts

import { Salon } from '@/types/salon';

export const AREAS = [
    '北海道', '茨城県', '栃木県', '埼玉県', '千葉県',
    '東京都', '神奈川県', '岐阜県', '愛知県', '京都府',
    '大阪府', '兵庫県', '奈良県', '和歌山県', '岡山県',
    '広島県', '愛媛県', '高知県', '福岡県', '海外'
];

export const MENUS = [
    'ハイトーン・カラー', 'パーマ', 'カット', 'ヘアメイク',
    '髪質改善', 'なんでも', 'メンズ特化', '縮毛',
    'ナチュラル', 'まつげ・ブロウ', 'ネイル', '特殊ヘア'
];

export const MOCK_SALONS: Salon[] = [
    { id: 1, name: 'トータルバランス美容サロン Oasis Ankh 円山店', location: '北海道', tags: ['髪質改善', 'ナチュラル'], imageType: 'canvas' },
    { id: 2, name: 'CreBiA hair & ESTHE', location: '愛知県', tags: ['髪質改善', '韓国'], imageType: 'canvas' },
    { id: 3, name: 'Rohange hair', location: '愛知県', tags: ['カット', 'ナチュラル'], imageType: 'canvas' },
    { id: 4, name: 'Rohange hair Creo', location: '岐阜県', tags: ['ナチュラル', '髪質改善'], imageType: 'canvas' },
    { id: 5, name: 'Miyu\'s Shibuya FLAG', location: '東京都', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 6, name: '髪質改善トリートメント&ヘッドスパ専門店LAPISUTA門前仲町', location: '東京都', tags: ['髪質改善'], imageType: 'canvas' },
    { id: 7, name: 'canvas. hair&make', location: '神奈川県', tags: ['ハイトーン・カラー', 'カット'], imageType: 'canvas' },
    { id: 8, name: 'QOO 戸越銀座 髪質改善', location: '東京都', tags: ['髪質改善', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 9, name: 'leap 祖師ヶ谷大蔵', location: '東京都', tags: ['なんでも', '髪質改善'], imageType: 'canvas' },
    { id: 10, name: 'OmShantiS', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 11, name: 'HOROS', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 12, name: 'ANell', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 13, name: 'tokute高円寺', location: '東京都', tags: ['ハイトーン・カラー', 'なんでも'], imageType: 'canvas' },
    { id: 14, name: 'HAIR&SHOES TypeAB', location: '神奈川県', tags: ['カット', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 15, name: 'アールヘアメイク', location: '兵庫県', tags: ['なんでも', '特殊ヘア'], imageType: 'canvas' },
    { id: 16, name: 'femme', location: '京都府', tags: ['なんでも'], imageType: 'canvas' },
    { id: 17, name: 'OF-HEARTS橋本店', location: '東京都', tags: ['カット', '髪質改善'], imageType: 'canvas' },
    { id: 18, name: 'OF-HEARTS八王子みなみ野店', location: '東京都', tags: ['髪質改善', 'メンズ特化'], imageType: 'canvas' },
    { id: 19, name: 'Anphi井土ヶ谷', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 20, name: 'Anphi弘明寺', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 21, name: 'Anphi新杉田', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 22, name: 'Anphi金沢文庫', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 23, name: 'Anphi南町田', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 24, name: 'Anphi矢向', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 25, name: 'Anphi鶴間', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 26, name: 'Anphi淵野辺', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 27, name: 'Anphi高座渋谷', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 28, name: 'Anphi神奈川新町', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 29, name: 'U-topia', location: '東京都', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 30, name: 'AIZU 本厚木店　海老名店　東海大前店　渋沢店どこでも可能', location: '神奈川県', tags: ['ハイトーン・カラー', 'メンズ特化'], imageType: 'canvas' },
    { id: 31, name: 'AIZU 海老名店', location: '神奈川県', tags: ['パーマ', 'メンズ特化'], imageType: 'canvas' },
    { id: 32, name: 'AIZU 本厚木店', location: '神奈川県', tags: ['ハイトーン・カラー', 'なんでも'], imageType: 'canvas' },
    { id: 33, name: 'AIZU 東海大前店', location: '神奈川県', tags: ['ハイトーン・カラー', 'メンズ特化'], imageType: 'canvas' },
    { id: 34, name: 'AIZU 渋沢店', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 35, name: '原宿ミラー', location: '東京都', tags: ['ハイトーン・カラー', 'カット'], imageType: 'canvas' },
    { id: 36, name: 'True Creation 渋谷', location: '東京都', tags: ['ハイトーン・カラー', 'メンズ特化'], imageType: 'canvas' },
    { id: 37, name: 'エクファ　シェリル店', location: '滋賀県', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 38, name: 'ex-fa hair-resort', location: '滋賀県', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 39, name: 'eyelash&nail salontent町田店', location: '東京都', tags: ['まつげ・ブロウ', 'ネイル'], imageType: 'canvas' },
    { id: 40, name: 'sins', location: '東京都', tags: ['髪質改善'], imageType: 'canvas' },
    { id: 41, name: 'Lond銀座', location: '東京都', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 42, name: 'Londfille銀座', location: '東京都', tags: ['カット', '韓国'], imageType: 'canvas' },
    { id: 43, name: 'Lond partir 大宮西口店', location: '埼玉県', tags: ['カット', 'パーマ'], imageType: 'canvas' },
    { id: 44, name: 'Lond un Maison. 原宿店', location: '東京都', tags: ['なんでも', 'カット'], imageType: 'canvas' },
    { id: 45, name: 'Lond omotesando', location: '埼玉県', tags: ['髪質改善', 'カット'], imageType: 'canvas' },
    { id: 46, name: 'Grandoeil by Lond', location: '東京都', tags: ['まつげ・ブロウ'], imageType: 'canvas' },
    { id: 47, name: 'Grand oeil toujours', location: '東京都', tags: ['まつげ・ブロウ'], imageType: 'canvas' },
    { id: 48, name: 'Grandoeil eclat', location: '東京都', tags: ['まつげ・ブロウ'], imageType: 'canvas' },
    { id: 49, name: 'Lond fleur 大宮東口', location: '埼玉県', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 50, name: 'Lond Loire 門前仲町店', location: '東京都', tags: ['なんでも', 'ナチュラル'], imageType: 'canvas' },
    { id: 51, name: 'Lond Loire 門前仲町店', location: '東京都', tags: ['なんでも', 'ナチュラル'], imageType: 'canvas' },
    { id: 52, name: 'OF-HEARTS若葉台店', location: '東京都', tags: ['カット', '髪質改善'], imageType: 'canvas' },
    { id: 53, name: 'Lond blanche 錦糸町北口', location: '東京都', tags: ['韓国', '髪質改善'], imageType: 'canvas' },
    { id: 54, name: 'Lond espoir錦糸町', location: '東京都', tags: ['カット', '韓国'], imageType: 'canvas' },
    { id: 55, name: 'Lond vallee 渋谷店', location: '東京都', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 56, name: 'terrace 銀座', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 57, name: 'Lond leglise', location: '東京都', tags: ['なんでも', 'カット'], imageType: 'canvas' },
    { id: 58, name: 'Lond rouge 銀座', location: '東京都', tags: ['カット', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 59, name: 'Lond avenir 北千住', location: '東京都', tags: ['髪質改善', 'カット'], imageType: 'canvas' },
    { id: 60, name: 'QUEEN\'S GARDEN by K-two　K-two GINZA', location: '東京都', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 61, name: 'K-two青山店', location: '東京都', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 62, name: 'K-two Esola　IKEBUKURO', location: '東京都', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 63, name: 'K-two名古屋店', location: '愛知県', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 64, name: 'k-two　kyoto　laque　emu', location: '京都府', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 65, name: 'corso', location: '大阪府', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 66, name: 'QUEEN\'S GARDEN by K-two  Shinsaibashi', location: '大阪府', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 67, name: 'Lond BOY', location: '東京都', tags: ['カット', '髪質改善'], imageType: 'canvas' },
    { id: 68, name: 'QUEEN\'S GARDEN by K-two　add', location: '大阪府', tags: ['なんでも', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 69, name: 'K-twoあべのキューズモール店', location: '大阪府', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 70, name: 'K-two 谷町店', location: '大阪府', tags: ['なんでも', 'カット'], imageType: 'canvas' },
    { id: 71, name: 'CORSO by k-two', location: '兵庫県', tags: ['なんでも', 'カット'], imageType: 'canvas' },
    { id: 72, name: 'Lond printemps', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 73, name: 'Lond Lily 銀座店', location: '東京都', tags: ['カット', '韓国'], imageType: 'canvas' },
    { id: 74, name: 'shell吉祥寺', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 75, name: 'tokute吉祥寺', location: '東京都', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 76, name: 'shell国分寺', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 77, name: 'shell立川', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 78, name: 'LODAT 横浜', location: '神奈川県', tags: ['なんでも', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 79, name: 'ヘアドゥ千葉店　他28店舗', location: '千葉県', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 80, name: 'BELLA', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 81, name: 'ヘアドゥ千葉店', location: '千葉県', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 82, name: 'ティアラ桜木町店', location: '神奈川県', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 83, name: '1+ Unplus lien', location: '東京都', tags: ['ナチュラル', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 84, name: 'arts ofa 町田', location: '東京都', tags: ['ヘアメイク', 'なんでも'], imageType: 'canvas' },
    { id: 85, name: 'arts 調布', location: '東京都', tags: ['なんでも', '髪質改善'], imageType: 'canvas' },
    { id: 86, name: 'arts 新宿', location: '東京都', tags: ['なんでも', '髪質改善'], imageType: 'canvas' },
    { id: 87, name: '1+ Unplus 市川店', location: '千葉県', tags: ['ハイトーン・カラー', 'カット'], imageType: 'canvas' },
    { id: 88, name: 'True Creation 北千住', location: '東京都', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 89, name: 'MEN\'S SALON True Craation 大宮', location: '埼玉県', tags: ['メンズ特化', '韓国'], imageType: 'canvas' },
    { id: 90, name: 'True Creation 新越谷', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 91, name: 'True Creation 久喜', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 92, name: 'True Creation 小山', location: '栃木県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 93, name: '半個室/髪質改善サロン L by True Creation', location: '埼玉県', tags: ['髪質改善', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 94, name: 'MEN\'S SALON SHINE', location: '埼玉県', tags: ['メンズ特化', '韓国'], imageType: 'canvas' },
    { id: 95, name: 'MEN\'S SALON EDEN', location: '埼玉県', tags: ['韓国', 'メンズ特化'], imageType: 'canvas' },
    { id: 96, name: '韓国カラー専門店 mignon', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 97, name: 'MEN\'S SALON Noah', location: '埼玉県', tags: ['メンズ特化', '韓国'], imageType: 'canvas' },
    { id: 98, name: 'elf', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 99, name: 'AERA by True Cration', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 100, name: 'True Creation 春日部', location: '埼玉県', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 101, name: 'SEED by Shamrock 横浜店', location: '神奈川県', tags: ['パーマ', 'カット'], imageType: 'canvas' },
    { id: 102, name: 'divine船橋', location: '千葉県', tags: ['パーマ', 'カット'], imageType: 'canvas' },
    { id: 103, name: 'オレンジポップ　南行徳店', location: '千葉県', tags: ['髪質改善', 'ヘアメイク'], imageType: 'canvas' },
    { id: 104, name: 'corst瑞江店', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 105, name: 'オレンジポップ　船堀店', location: '東京都', tags: ['カット', 'パーマ'], imageType: 'canvas' },
    { id: 106, name: 'オレンジポップ　検見川浜店', location: '千葉県', tags: ['ヘアメイク', '韓国'], imageType: 'canvas' },
    { id: 107, name: 'オレンジポップ　妙典店', location: '千葉県', tags: ['髪質改善', '韓国'], imageType: 'canvas' },
    { id: 108, name: 'オレンジポップ　蘇我店', location: '千葉県', tags: ['髪質改善', 'カット'], imageType: 'canvas' },
    { id: 109, name: 'オレンジポップ　流山おおたかの森店', location: '千葉県', tags: ['髪質改善', 'カット'], imageType: 'canvas' },
    { id: 110, name: 'オレンジポップ　南船橋店', location: '千葉県', tags: ['メンズ特化', '韓国'], imageType: 'canvas' },
    { id: 111, name: '希望店舗（新卒者は全店必須）', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 112, name: 'オートクチュール　ランコントレ　本店', location: '京都府', tags: ['なんでも', 'ナチュラル'], imageType: 'canvas' },
    { id: 113, name: 'aell', location: '京都府', tags: ['髪質改善', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 114, name: 'ULHA SALON', location: '京都府', tags: ['カット', '髪質改善'], imageType: 'canvas' },
    { id: 115, name: 'REMY', location: '京都府', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 116, name: '.SUI', location: '京都府', tags: ['ハイトーン・カラー', 'パーマ'], imageType: 'canvas' }
];