import { Salon } from '@/types/salon';

export const MOCK_SALONS: Salon[] = [
    { 
        id: 1, 
        name: 'トータルバランス美容サロン Oasis Ankh 円山店', 
        location: '北海道',
        images:{image1:'/salon1-1.png',image2:'/salon1-2.png'},
        address:'北海道札幌市中央区大通西24丁目1-10アルファ円山3階', 
        nameKana:'オアシスアンク マルヤマテン',
        tags: ['髪質改善', 'ナチュラル'], 
        imageType: 'canvas',
        visitSchedule:'毎月第2水曜日、金曜日、日曜日 他日程も可',
        duration:'16:00～（1時間程）、他時間帯も対応可',
        flow:'企業概要の説明→美容サロンの説明→サロン案内→質問や交流時間',
        guideStaff:'小原',
        contact:'小原 木聖',
        instagram:'https://www.instagram.com/oasis_ankh/',
        meetingPlace:'https://www.ankh-jp.com/access/',
        staffGenderRatio:'女性多め',
        staffAgeGroup:'年齢に偏りなし',
        atmosphere:'仕事重視',
        customerGenderRatio:'女性90:男性10',
        customerAgeGroup:'40代',
        internationalCustomerFrequency:'外国人多い',
    },{
        id: 2,
        name: 'CreBiA hair & ESTHE',
        location: '愛知県',
        address: '名古屋市中村区名駅南1丁目28-26宇徳ビル2F',
        nameKana: 'クレビアヘアーアンドエステ',
        tags: ['髪質改善', '韓国'],
        imageType: 'canvas',
        visitSchedule: '未定',
        duration: '未定',
        flow: 'サロン説明',
        guideStaff: '未定',
        instagram: 'https://www.instagram.com/crebia.hair.esthe/',
        meetingPlace: 'https://maps.app.goo.gl/tsVh5YGefjgqwjiM7?g_st=com.google.maps.preview.copy',
        staffGenderRatio: '女性多め',
        staffAgeGroup: '20～30代',
        atmosphere: 'プライベート重視',
        customerGenderRatio: '女性8:男性2',
        customerAgeGroup: '～20代',
        internationalCustomerFrequency: '外国人少ない',
    },
    {
        id: 3,
        name: 'Rohange hair',
        location: '愛知県',
        address: '愛知県名古屋市中村区名駅4-26-23名駅エフワンビル8F',
        nameKana: 'ラファンジュヘアー',
        tags: ['カット', 'ナチュラル'],
        imageType: 'canvas',
        visitSchedule: '未定',
        duration: '未定',
        flow: 'サロン見学',
        guideStaff: '未定',
        instagram: 'https://www.instagram.com/rohangehair/',
        meetingPlace: 'https://www.google.com/maps/place/〒450-0002+愛知県名古屋市中村区名駅４丁目２６－２３+名駅エフワンビル+8F+ラファンジュヘアー/',
        staffGenderRatio: '男女同じくらい',
        staffAgeGroup: '20～30代',
        atmosphere: 'プライベート重視',
        customerGenderRatio: '女性8:男性2',
        customerAgeGroup: '30代',
        internationalCustomerFrequency: '外国人少ない',
    },
    {
        id: 4,
        name: 'Rohange hair Creo',
        location: '岐阜県',
        address: '岐阜県岐阜市神田町9-22',
        nameKana: 'ラファンジュヘアークレオ',
        tags: ['ナチュラル', '髪質改善'],
        imageType: 'canvas',
        visitSchedule: '未定',
        duration: '未定',
        flow: 'サロン見学',
        guideStaff: '未定',
        instagram: 'https://www.instagram.com/rohange_creo/',
        meetingPlace: 'https://www.google.com/maps/place//data=!4m2!3m1!1s0x6003a9383618c489:0xbb8aae4e0cd9573c',
        staffGenderRatio: '男女同じくらい',
        staffAgeGroup: '20～30代',
        atmosphere: 'プライベート重視',
        customerGenderRatio: '女性7:男性3',
        customerAgeGroup: '30代',
        internationalCustomerFrequency: '外国人少ない',
    },
    {
        id: 5,
        name: "Miyu's Shibuya FLAG",
        location: '東京都',
        images: { image1: '/salon5-1.png', image2: '/salon5-2.png' },
        address: '東京都渋谷区宇田川町33-6 ShibuyaFLAG 9階',
        nameKana: 'ミユーズ シブヤ フラッグ',
        tags: ['カット', 'オールラウンダー（なんでも）'],
        imageType: 'canvas',
        visitSchedule: '随時相談',
        duration: '1時間',
        flow: 'サロン見学→会社説明→スタッフとの交流',
        guideStaff: '長谷川',
        instagram: 'https://www.instagram.com/miyus_hasegawa/',
        meetingPlace: 'https://www.google.com/maps/place/〒150-0042+東京都渋谷区宇田川町３３－６+渋谷フラッグビル/',
        staffGenderRatio: '男女同じくらい',
        staffAgeGroup: '20～30代',
        atmosphere: 'プライベート重視',
        customerGenderRatio: '女性50:男性50',
        customerAgeGroup: '～20代',
        internationalCustomerFrequency: '外国人多い',
    },
    {
        id: 6,
        name: '髪質改善トリートメント&ヘッドスパ専門店LAPISUTA門前仲町',
        location: '東京都',
        images: { image1: '/salon6-1.png', image2: '/salon6-2.png' },
        address: '東京都江東区富岡1-23-15 西村ビル102',
        nameKana: 'カミシツカイゼントリートメントアンドヘッドスパセンモンテンラピスタモンゼンナカチョウ',
        tags: ['髪質改善'],
        imageType: 'canvas',
        visitSchedule: '10～20時の営業中、時間外も可',
        duration: '30分～1時間',
        flow: 'サロン見学→ヒアリング→会社説明→採用連絡',
        guideStaff: '代表 成川陽介',
        instagram: 'https://www.instagram.com/naru_lapisuta_hair/',
        meetingPlace: 'https://www.google.com/search?q=門前仲町美容室LAPISUTSA髪質改善トリートメント&ヘッドスパ専門店',
        staffGenderRatio: '男女同じくらい',
        staffAgeGroup: '年齢に偏りなし',
        atmosphere: '仕事重視',
        customerGenderRatio: '女性100',
        customerAgeGroup: '40代',
        internationalCustomerFrequency: '外国人少ない',
    },
    {
        id: 7,
        name: 'canvas. hair&make',
        location: '神奈川県',
        images: { image1: '/salon7-1.png', image2: '/salon7-2.png' },
        address: '神奈川県川崎市幸区大宮町16-1',
        nameKana: 'キャンバス ヘアーアンドメイク',
        tags: ['ハイトーン・カラー', 'カット'],
        imageType: 'canvas',
        visitSchedule: '随時',
        duration: '11時～20時の間の1時間',
        flow: 'サロン見学①(canvas.)→サロン見学②(canvas anew.)→会社説明及びスタッフとの交流',
        guideStaff: '小山崎裕士 西田莉那',
        instagram: 'https://www.instagram.com/canvas.hair_recruit/',
        meetingPlace: 'https://maps.app.goo.gl/5sWEVGGynGdArZwi8?g_st=com.google.maps.preview.copy',
        staffGenderRatio: '女性多め',
        staffAgeGroup: '20～30代',
        atmosphere: 'プライベート重視',
        customerGenderRatio: '女性65%: 男性35%',
        customerAgeGroup: '30代',
        internationalCustomerFrequency: '外国人少ない',
    },
    {
        id: 8,
        name: 'QOO 戸越銀座 髪質改善',
        location: '東京都',
        images: { image1: '/salon8-1.png', image2: '/salon8-2.png' },
        address: '東京都品川区平塚3-4-2 エムズ戸越銀座3F',
        nameKana: 'クー トゴシギンザ カミシツカイゼン',
        tags: ['髪質改善', 'ハイトーン・カラー'],
        imageType: 'canvas',
        visitSchedule: '定休日火曜以外全時間対応(予約によるので細かくは要相談)',
        duration: '1時間。営業時間内、営業時間前後の可',
        flow: 'サロン見学(店内見学、使用薬剤など説明、質疑応答タイム)',
        guideStaff: '小野里太',
        instagram: 'https://www.instagram.com/no1.haircare.togoshi/',
        meetingPlace: 'https://g.co/kgs/va8dHZT',
        staffGenderRatio: '男性多め',
        staffAgeGroup: '20～30代',
        atmosphere: 'プライベート重視',
        customerGenderRatio: '女性7:男性3',
        customerAgeGroup: '30代',
        internationalCustomerFrequency: '外国人少ない',
    },
    { id: 9, name: 'leap 祖師ヶ谷大蔵', location: '東京都', tags: ['なんでも', '髪質改善'], imageType: 'canvas' },
    { id: 10, name: 'OmShantiS', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 11, name: 'HOROS', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 12, name: 'ANell', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 13, name: 'tokute高円寺', location: '東京都', tags: ['ハイトーン・カラー', 'なんでも'], imageType: 'canvas' },
    { id: 14, name: 'HAIR&SHOES TypeAB', location: '神奈川県', tags: ['カット', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 15, name: 'アールヘアメイク', location: '兵庫県', tags: ['なんでも', '特殊ヘア'], imageType: 'canvas' },
    { id: 16, name: 'femme', location: '京都府', tags: ['なんでも'], imageType: 'canvas' },
    { id: 17, name: 'OF-HEARTS橋本店', location: '東京都', tags: ['カット', '髪質改善'], imageType: 'canvas' },
    { id: 18, name: 'OF-HEARTS八王子みなみ野店', location: '東京都', tags: ['髪質改善', 'メンズ特化'], imageType: 'canvas' },
    { id: 19, name: 'Anphi井土ヶ谷', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 20, name: 'Anphi弘明寺', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 21, name: 'Anphi新杉田', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 22, name: 'Anphi金沢文庫', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 23, name: 'Anphi南町田', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 24, name: 'Anphi矢向', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 25, name: 'Anphi鶴間', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 26, name: 'Anphi淵野辺', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 27, name: 'Anphi高座渋谷', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 28, name: 'Anphi神奈川新町', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 29, name: 'U-topia', location: '東京都', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 30, name: 'AIZU 本厚木店　海老名店　東海大前店　渋沢店どこでも可能', location: '神奈川県', tags: ['ハイトーン・カラー', 'メンズ特化'], imageType: 'canvas' },
    { id: 31, name: 'AIZU 海老名店', location: '神奈川県', tags: ['パーマ', 'メンズ特化'], imageType: 'canvas' },
    { id: 32, name: 'AIZU 本厚木店', location: '神奈川県', tags: ['ハイトーン・カラー', 'なんでも'], imageType: 'canvas' },
    { id: 33, name: 'AIZU 東海大前店', location: '神奈川県', tags: ['ハイトーン・カラー', 'メンズ特化'], imageType: 'canvas' },
    { id: 34, name: 'AIZU 渋沢店', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 35, name: '原宿ミラー', location: '東京都', tags: ['ハイトーン・カラー', 'カット'], imageType: 'canvas' },
    { id: 36, name: 'True Creation 渋谷', location: '東京都', tags: ['ハイトーン・カラー', 'メンズ特化'], imageType: 'canvas' },
    { id: 37, name: 'エクファ　シェリル店', location: '滋賀県', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 38, name: 'ex-fa hair-resort', location: '滋賀県', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 39, name: 'eyelash&nail salontent町田店', location: '東京都', tags: ['まつげ・ブロウ', 'ネイル'], imageType: 'canvas' },
    { id: 40, name: 'sins', location: '東京都', tags: ['髪質改善'], imageType: 'canvas' },
    { id: 41, name: 'Lond銀座', location: '東京都', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 42, name: 'Londfille銀座', location: '東京都', tags: ['カット', '韓国'], imageType: 'canvas' },
    { id: 43, name: 'Lond partir 大宮西口店', location: '埼玉県', tags: ['カット', 'パーマ'], imageType: 'canvas' },
    { id: 44, name: 'Lond un Maison. 原宿店', location: '東京都', tags: ['なんでも', 'カット'], imageType: 'canvas' },
    { id: 45, name: 'Lond omotesando', location: '埼玉県', tags: ['髪質改善', 'カット'], imageType: 'canvas' },
    { id: 46, name: 'Grandoeil by Lond', location: '東京都', tags: ['まつげ・ブロウ'], imageType: 'canvas' },
    { id: 47, name: 'Grand oeil toujours', location: '東京都', tags: ['まつげ・ブロウ'], imageType: 'canvas' },
    { id: 48, name: 'Grandoeil eclat', location: '東京都', tags: ['まつげ・ブロウ'], imageType: 'canvas' },
    { id: 49, name: 'Lond fleur 大宮東口', location: '埼玉県', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 50, name: 'Lond Loire 門前仲町店', location: '東京都', tags: ['なんでも', 'ナチュラル'], imageType: 'canvas' },
    { id: 51, name: 'Lond Loire 門前仲町店', location: '東京都', tags: ['なんでも', 'ナチュラル'], imageType: 'canvas' },
    { id: 52, name: 'OF-HEARTS若葉台店', location: '東京都', tags: ['カット', '髪質改善'], imageType: 'canvas' },
    { id: 53, name: 'Lond blanche 錦糸町北口', location: '東京都', tags: ['韓国', '髪質改善'], imageType: 'canvas' },
    { id: 54, name: 'Lond espoir錦糸町', location: '東京都', tags: ['カット', '韓国'], imageType: 'canvas' },
    { id: 55, name: 'Lond vallee 渋谷店', location: '東京都', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 56, name: 'terrace 銀座', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 57, name: 'Lond leglise', location: '東京都', tags: ['なんでも', 'カット'], imageType: 'canvas' },
    { id: 58, name: 'Lond rouge 銀座', location: '東京都', tags: ['カット', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 59, name: 'Lond avenir 北千住', location: '東京都', tags: ['髪質改善', 'カット'], imageType: 'canvas' },
    { id: 60, name: 'QUEEN\'S GARDEN by K-two　K-two GINZA', location: '東京都', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 61, name: 'K-two青山店', location: '東京都', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 62, name: 'K-two Esola　IKEBUKURO', location: '東京都', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 63, name: 'K-two名古屋店', location: '愛知県', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 64, name: 'k-two　kyoto　laque　emu', location: '京都府', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 65, name: 'corso', location: '大阪府', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 66, name: 'QUEEN\'S GARDEN by K-two  Shinsaibashi', location: '大阪府', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 67, name: 'Lond BOY', location: '東京都', tags: ['カット', '髪質改善'], imageType: 'canvas' },
    { id: 68, name: 'QUEEN\'S GARDEN by K-two　add', location: '大阪府', tags: ['なんでも', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 69, name: 'K-twoあべのキューズモール店', location: '大阪府', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 70, name: 'K-two 谷町店', location: '大阪府', tags: ['なんでも', 'カット'], imageType: 'canvas' },
    { id: 71, name: 'CORSO by k-two', location: '兵庫県', tags: ['なんでも', 'カット'], imageType: 'canvas' },
    { id: 72, name: 'Lond printemps', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 73, name: 'Lond Lily 銀座店', location: '東京都', tags: ['カット', '韓国'], imageType: 'canvas' },
    { id: 74, name: 'shell吉祥寺', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 75, name: 'tokute吉祥寺', location: '東京都', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 76, name: 'shell国分寺', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 77, name: 'shell立川', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 78, name: 'LODAT 横浜', location: '神奈川県', tags: ['なんでも', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 79, name: 'ヘアドゥ千葉店　他28店舗', location: '千葉県', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 80, name: 'BELLA', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 81, name: 'ヘアドゥ千葉店', location: '千葉県', tags: ['カット', 'なんでも'], imageType: 'canvas' },
    { id: 82, name: 'ティアラ桜木町店', location: '神奈川県', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 83, name: '1+ Unplus lien', location: '東京都', tags: ['ナチュラル', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 84, name: 'arts ofa 町田', location: '東京都', tags: ['ヘアメイク', 'なんでも'], imageType: 'canvas' },
    { id: 85, name: 'arts 調布', location: '東京都', tags: ['なんでも', '髪質改善'], imageType: 'canvas' },
    { id: 86, name: 'arts 新宿', location: '東京都', tags: ['なんでも', '髪質改善'], imageType: 'canvas' },
    { id: 87, name: '1+ Unplus 市川店', location: '千葉県', tags: ['ハイトーン・カラー', 'カット'], imageType: 'canvas' },
    { id: 88, name: 'True Creation 北千住', location: '東京都', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 89, name: 'MEN\'S SALON True Craation 大宮', location: '埼玉県', tags: ['メンズ特化', '韓国'], imageType: 'canvas' },
    { id: 90, name: 'True Creation 新越谷', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 91, name: 'True Creation 久喜', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 92, name: 'True Creation 小山', location: '栃木県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 93, name: '半個室/髪質改善サロン L by True Creation', location: '埼玉県', tags: ['髪質改善', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 94, name: 'MEN\'S SALON SHINE', location: '埼玉県', tags: ['メンズ特化', '韓国'], imageType: 'canvas' },
    { id: 95, name: 'MEN\'S SALON EDEN', location: '埼玉県', tags: ['韓国', 'メンズ特化'], imageType: 'canvas' },
    { id: 96, name: '韓国カラー専門店 mignon', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 97, name: 'MEN\'S SALON Noah', location: '埼玉県', tags: ['メンズ特化', '韓国'], imageType: 'canvas' },
    { id: 98, name: 'elf', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 99, name: 'AERA by True Cration', location: '埼玉県', tags: ['ハイトーン・カラー', '韓国'], imageType: 'canvas' },
    { id: 100, name: 'True Creation 春日部', location: '埼玉県', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 101, name: 'SEED by Shamrock 横浜店', location: '神奈川県', tags: ['パーマ', 'カット'], imageType: 'canvas' },
    { id: 102, name: 'divine船橋', location: '千葉県', tags: ['パーマ', 'カット'], imageType: 'canvas' },
    { id: 103, name: 'オレンジポップ　南行徳店', location: '千葉県', tags: ['髪質改善', 'ヘアメイク'], imageType: 'canvas' },
    { id: 104, name: 'corst瑞江店', location: '東京都', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 105, name: 'オレンジポップ　船堀店', location: '東京都', tags: ['カット', 'パーマ'], imageType: 'canvas' },
    { id: 106, name: 'オレンジポップ　検見川浜店', location: '千葉県', tags: ['ヘアメイク', '韓国'], imageType: 'canvas' },
    { id: 107, name: 'オレンジポップ　妙典店', location: '千葉県', tags: ['髪質改善', '韓国'], imageType: 'canvas' },
    { id: 108, name: 'オレンジポップ　蘇我店', location: '千葉県', tags: ['髪質改善', 'カット'], imageType: 'canvas' },
    { id: 109, name: 'オレンジポップ　流山おおたかの森店', location: '千葉県', tags: ['髪質改善', 'カット'], imageType: 'canvas' },
    { id: 110, name: 'オレンジポップ　南船橋店', location: '千葉県', tags: ['メンズ特化', '韓国'], imageType: 'canvas' },
    { id: 111, name: '希望店舗（新卒者は全店必須）', location: '神奈川県', tags: ['髪質改善', 'なんでも'], imageType: 'canvas' },
    { id: 112, name: 'オートクチュール　ランコントレ　本店', location: '京都府', tags: ['なんでも', 'ナチュラル'], imageType: 'canvas' },
    { id: 113, name: 'aell', location: '京都府', tags: ['髪質改善', 'ハイトーン・カラー'], imageType: 'canvas' },
    { id: 114, name: 'ULHA SALON', location: '京都府', tags: ['カット', '髪質改善'], imageType: 'canvas' },
    { id: 115, name: 'REMY', location: '京都府', tags: ['ハイトーン・カラー', '髪質改善'], imageType: 'canvas' },
    { id: 116, name: '.SUI', location: '京都府', tags: ['ハイトーン・カラー', 'パーマ'], imageType: 'canvas' }
];